### ISSUE TITLE
Receiving error attempting to start script

### ISSUE THREAD

**Issue by Mexiemeal** [WookieeNo1/NGUIdleInjector-Pretty-Print#8]
When I attempt to run the file on Inject.log in tail mode, I get the following error message:

7/6/2022-3:26 PM   : Casting Failed Casting number blood spell before rebirth -
Resetting title to PowerShell
ProcessLines: D:\NGUIdleInjector-Pretty-Print-master\ParseNGUInjector_tools.ps1:1317
Line |
1317 |  … ocation() -Tail $MaxTailItems -Wait | ForEach-Object { ProcessLines }
     |                                                           ~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.
[tmp-Inject.log.txt](https://github.com/WookieeNo1/NGUIdleInjector-Pretty-Print/files/9057938/tmp-Inject.log.txt)
.

**Comment by WookieeNo1** [comment]
I guess you're using the tomerpeleg-pub/NGUInjector? I have only just become aware of that fork... 

I'll get on to it, please bear with me

**Comment by Mexiemeal** [comment]
That is the fork I am using. So many different forks now it seems. I appreciate the quick response, no rush on it. Just thought I would report it not realizing your project was used on a different fork.

**Comment by WookieeNo1** [comment]
I just need to compare the 2 sets of source files for new output, a cursory view seems to show this is the only major difference in the Inject.log, and the new message is being confused with the earlier "Casting Failed" message, hence the crash. Shouldn't be too difficult to fix, but it'll be a day or so before I get the chance to test properly.

**Comment by WookieeNo1** [comment]
Latest update should fix this issue, sorry for the delay
